### ISSUE TITLE
Remove Google Docs from the process

### ISSUE THREAD

**Issue by tripleee** [unicorn-meta-zoo/unicorn-meta-zoo.github.io#4]
I'd be vaguely happy to volunteer to participate in transcriptions, but the current process apparently involves Google Docs, which I would like to avoid. Is there a way to adjust the process to one which does not involve leaking your every move to our overlords at Big G?

**Comment by jericson** [comment]
At the moment we're falling behind the transcription process, so I didn't send out the most recent episode. For episode 3, I did set up a private Gist instead of a Google doc. That worked fine, but it risks people duplicating work. (Most people start a transcription at the start of the show. One option would be have people sign up for a timeslot before they start transcription work, so it's a solvable problem.) 

Since we need the most help [updating the wiki](https://github.com/unicorn-meta-zoo/unicorn-meta-zoo.github.io/wiki) for published episodes, there's no need for Google Docs.

**Comment by jericson** [comment]
I [changed the reference from Google Docs to maybe a Gist](https://github.com/unicorn-meta-zoo/unicorn-meta-zoo.github.io/commit/f171d64d2320609df6515d98a389b1d0e0ae4783).
